#!/usr/bin/env python3
"""
api.py — FastAPI microservice for EG diagram cropping
======================================================
POST /crop        Upload a PDF → receive a ZIP of cropped PNGs + metadata.json
GET  /health      Liveness probe (used by Render)
GET  /docs        Swagger UI (auto-generated by FastAPI)
"""

import io
import json
import logging
import math
import tempfile
import zipfile
from pathlib import Path
from typing import Annotated

import cv2
import numpy as np
import pymupdf
from fastapi import FastAPI, File, HTTPException, Query, UploadFile
from fastapi.responses import Response, StreamingResponse

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Diagram Cropper",
    description=(
        "Extracts Existential Graph diagrams from PDFs using a two-pass "
        "vector + contour detection strategy. Returns a ZIP archive "
        "containing numbered PNG crops and a metadata.json manifest."
    ),
    version="1.0.0",
)


# ── Detection helpers (ported from crop_eg_diagrams.py) ──────────────────────

def merge_nearby_rects(rects: list[tuple], gap: float = 70) -> list[tuple]:
    if not rects:
        return []
    rects = list(rects)
    used = [False] * len(rects)
    merged = []
    for i, (ax0, ay0, ax1, ay1) in enumerate(rects):
        if used[i]:
            continue
        x0, y0, x1, y1 = ax0, ay0, ax1, ay1
        changed = True
        while changed:
            changed = False
            for j, (bx0, by0, bx1, by1) in enumerate(rects):
                if used[j] or j == i:
                    continue
                if bx0 <= x1 + gap and bx1 >= x0 - gap and by0 <= y1 + gap and by1 >= y0 - gap:
                    x0, y0 = min(x0, bx0), min(y0, by0)
                    x1, y1 = max(x1, bx1), max(y1, by1)
                    used[j] = True
                    changed = True
        merged.append((x0, y0, x1, y1))
        used[i] = True
    return merged


def iou(a: tuple, b: tuple) -> float:
    ax0, ay0, ax1, ay1 = a
    bx0, by0, bx1, by1 = b
    ix0, iy0 = max(ax0, bx0), max(ay0, by0)
    ix1, iy1 = min(ax1, bx1), min(ay1, by1)
    if ix1 <= ix0 or iy1 <= iy0:
        return 0.0
    inter = (ix1 - ix0) * (iy1 - iy0)
    area_a = (ax1 - ax0) * (ay1 - ay0)
    area_b = (bx1 - bx0) * (by1 - by0)
    return inter / min(area_a, area_b) if min(area_a, area_b) > 0 else 0.0


def deduplicate(boxes: list[tuple], overlap_thresh: float = 0.4) -> list[tuple]:
    if not boxes:
        return []
    boxes = sorted(boxes, key=lambda b: (b[2] - b[0]) * (b[3] - b[1]), reverse=True)
    keep = []
    suppressed = [False] * len(boxes)
    for i, a in enumerate(boxes):
        if suppressed[i]:
            continue
        keep.append(a)
        for j, b in enumerate(boxes):
            if j > i and not suppressed[j] and iou(a, b) > overlap_thresh:
                suppressed[j] = True
    return keep


def detect_contour(
    img: np.ndarray,
    min_w: int,
    min_h: int,
    max_w_frac: float,
    min_ink_area: int = 2500,
) -> list[tuple]:
    h, w = img.shape[:2]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, bw = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY_INV)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (28, 18))
    dilated = cv2.dilate(bw, kernel, iterations=2)
    contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    boxes = []
    for cnt in contours:
        x, y, cw, ch = cv2.boundingRect(cnt)
        if cw < min_w or ch < min_h:
            continue
        if cw > w * max_w_frac:
            continue
        if cw / max(ch, 1) < 0.25:
            continue
        roi = bw[y : y + ch, x : x + cw]
        if int(roi.sum()) // 255 < min_ink_area:
            continue
        boxes.append((x, y, x + cw, y + ch))
    return boxes


def detect_vector(
    page: pymupdf.Page,
    scale: float,
    min_w_px: int,
    min_h_px: int,
    max_w_frac: float,
    img_w: int,
    gap_pt: float = 65,
) -> list[tuple]:
    drawings = page.get_drawings()
    if not drawings:
        return []
    rects_pt = [
        (d["rect"].x0, d["rect"].y0, d["rect"].x1, d["rect"].y1)
        for d in drawings
    ]
    clusters = merge_nearby_rects(rects_pt, gap=gap_pt)
    boxes = []
    for x0, y0, x1, y1 in clusters:
        px0, py0 = int(x0 * scale), int(y0 * scale)
        px1, py1 = int(x1 * scale), int(y1 * scale)
        cw, ch = px1 - px0, py1 - py0
        if cw < min_w_px or ch < min_h_px:
            continue
        if cw > img_w * max_w_frac:
            continue
        boxes.append((px0, py0, px1, py1))
    return boxes


# ── Core processing function ──────────────────────────────────────────────────

def process_pdf(
    pdf_bytes: bytes,
    dpi: float = 200,
    pad: int = 25,
    min_w: int = 60,
    min_h: int = 80,
    max_w_frac: float = 0.82,
) -> tuple[list[dict], list[tuple[str, bytes]]]:
    """
    Run the two-pass detector on all pages of a PDF.

    Returns
    -------
    metadata : list of dicts (one per crop)
    crops    : list of (filename, png_bytes)
    """
    doc = pymupdf.open(stream=pdf_bytes, filetype="pdf")
    scale = dpi / 72.0

    vector_pages = {p for p in range(len(doc)) if doc[p].get_drawings()}
    log.info("Pages with vector drawings: %s", sorted(p + 1 for p in vector_pages))

    metadata: list[dict] = []
    crops: list[tuple[str, bytes]] = []
    crop_id = 0

    for page_idx in range(len(doc)):
        page = doc[page_idx]
        page_num = page_idx + 1

        mat = pymupdf.Matrix(scale, scale)
        pix = page.get_pixmap(matrix=mat)
        img_data = np.frombuffer(pix.samples, dtype=np.uint8).reshape(
            pix.height, pix.width, pix.n
        )
        img = (
            cv2.cvtColor(img_data, cv2.COLOR_RGBA2BGR)
            if pix.n == 4
            else cv2.cvtColor(img_data, cv2.COLOR_RGB2BGR)
        )
        h_img, w_img = img.shape[:2]

        boxes_v = []
        if page_idx in vector_pages:
            boxes_v = detect_vector(
                page, scale,
                min_w_px=min_w, min_h_px=min_h,
                max_w_frac=max_w_frac, img_w=w_img,
            )

        boxes_c = detect_contour(img, min_w=min_w, min_h=min_h, max_w_frac=max_w_frac)

        all_boxes = list(boxes_v)
        for cb in boxes_c:
            if not any(iou(cb, vb) > 0.35 for vb in boxes_v):
                all_boxes.append(cb)

        all_boxes = deduplicate(all_boxes, overlap_thresh=0.4)

        if not all_boxes:
            continue

        log.info("Page %2d: %d region(s)", page_num, len(all_boxes))

        for x0, y0, x1, y1 in all_boxes:
            px0 = max(0, x0 - pad)
            py0 = max(0, y0 - pad)
            px1 = min(w_img, x1 + pad)
            py1 = min(h_img, y1 + pad)

            crop = img[py0:py1, px0:px1]
            if crop.size == 0:
                continue

            fname = f"eg_{crop_id:03d}_page{page_num:02d}.png"
            ok, buf = cv2.imencode(".png", crop)
            if not ok:
                log.warning("Failed to encode crop %s", fname)
                continue

            crops.append((fname, buf.tobytes()))
            metadata.append(
                {
                    "id": crop_id,
                    "filename": fname,
                    "source_page": page_num,
                    "bbox_page_px": [
                        int(px0), int(py0),
                        int(px1 - px0), int(py1 - py0),
                    ],
                    "page_wh_px": [int(w_img), int(h_img)],
                    "dpi": dpi,
                }
            )
            crop_id += 1

    doc.close()
    return metadata, crops


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["ops"])
def health() -> dict:
    """Liveness probe — returns 200 OK when the service is ready."""
    return {"status": "ok"}


@app.post(
    "/crop",
    tags=["processing"],
    summary="Extract EG diagram crops from a PDF",
    response_description="ZIP archive: PNG crops + metadata.json",
)
async def crop_pdf(
    file: Annotated[UploadFile, File(description="PDF to process")],
    dpi: Annotated[float, Query(ge=72, le=400, description="Rasterisation DPI")] = 200,
    pad: Annotated[int, Query(ge=0, le=200, description="Padding around each crop (px)")] = 25,
    min_w: Annotated[int, Query(ge=1, description="Min crop width (px)")] = 60,
    min_h: Annotated[int, Query(ge=1, description="Min crop height (px)")] = 80,
    max_w_frac: Annotated[float, Query(ge=0.1, le=1.0, description="Max crop width as fraction of page")] = 0.82,
) -> StreamingResponse:
    """
    Upload a PDF; receive a ZIP containing:

    - `eg_000_page02.png`, `eg_001_page03.png`, … — one PNG per detected diagram
    - `metadata.json` — bbox, page, DPI for every crop

    All detection parameters are tunable via query string.
    """
    if file.content_type not in ("application/pdf", "application/octet-stream"):
        raise HTTPException(
            status_code=415,
            detail=f"Expected a PDF, got content-type '{file.content_type}'",
        )

    pdf_bytes = await file.read()
    if not pdf_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty")

    log.info(
        "Processing '%s'  size=%d bytes  dpi=%.0f  pad=%d",
        file.filename, len(pdf_bytes), dpi, pad,
    )

    try:
        metadata, crops = process_pdf(
            pdf_bytes, dpi=dpi, pad=pad,
            min_w=min_w, min_h=min_h, max_w_frac=max_w_frac,
        )
    except Exception as exc:
        log.exception("Processing failed")
        raise HTTPException(status_code=500, detail=f"Processing failed: {exc}") from exc

    if not crops:
        raise HTTPException(
            status_code=422,
            detail="No diagram regions detected. Try adjusting dpi / min_w / min_h.",
        )

    # Build ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for fname, png_bytes in crops:
            zf.writestr(fname, png_bytes)
        zf.writestr("metadata.json", json.dumps(metadata, indent=2))
    zip_buffer.seek(0)

    stem = Path(file.filename or "output").stem
    zip_name = f"{stem}_crops.zip"
    log.info("Returning ZIP '%s' with %d crops", zip_name, len(crops))

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{zip_name}"'},
    )